# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.7"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.10.7"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  name = "github.com/chankh/eksutil"
  branch = "master"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.6.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[prune]
  go-tests = true
  unused-packages = true

