AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eks-lambda-drainer
  
  SAM Template for eks-lambda-drainer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  MyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./main.zip
      Handler: main
      Runtime: go1.x
      Policies:
        - AWSLambdaBasicExecutionRole # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:DescribeTags
                - eks:DescribeCluster
                - autoscaling:CompleteLifecycleAction
              Resource: '*'
      Events:
        CWE1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type: 
                - "EC2 Spot Instance Interruption Warning"
        CWE2:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.autoscaling
              detail-type: 
                -  "EC2 Instance-terminate Lifecycle Action"


Outputs:
  MyFunction:
    Description: "Lambda function Arn"
    Value: !GetAtt MyFunction.Arn

  MyFunctionIamRole:
    Description: "Lambda function IAM role Arn"
    Value: !GetAtt MyFunctionRole.Arn